# Generated by Django 3.2.12 on 2022-02-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teams_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='team_id',
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app1.teams'),
            preserve_default=False,
        ),
    ]
